branch-defaults:
  master:
    environment: Ticketgrace1
environment-defaults:
  Ticketgrace1:
    branch: null
    repository: null
global:
  application_name: ticketgrace
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/PHP 7.2 running on
    64bit Amazon Linux/2.8.15
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
